# Generated by Django 5.0.1 on 2024-03-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('num_test_matches', models.IntegerField()),
                ('num_t20_matches', models.IntegerField()),
                ('num_world_cup_matches', models.IntegerField()),
                ('num_odis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ranking', models.IntegerField()),
                ('num_batsmen', models.IntegerField(default=0)),
                ('num_bowlers', models.IntegerField(default=0)),
                ('wicketkeeper', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Umpire',
            fields=[
                ('umpire_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('num_matches', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Batsman',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Myapp.player')),
                ('num_sixes', models.IntegerField()),
                ('num_fours', models.IntegerField()),
                ('batting_average', models.FloatField()),
                ('total_runs', models.IntegerField()),
            ],
            bases=('Myapp.player',),
        ),
        migrations.CreateModel(
            name='Bowler',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Myapp.player')),
                ('batsman_type', models.CharField(max_length=100)),
                ('num_wickets', models.IntegerField()),
                ('economy', models.FloatField()),
            ],
            bases=('Myapp.player',),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.team'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('captain_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('num_years_captaincy', models.IntegerField()),
                ('num_wins', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('team1_name', models.CharField(max_length=100)),
                ('team2_name', models.CharField(max_length=100)),
                ('stadium', models.CharField(max_length=100)),
                ('winner_team', models.CharField(max_length=100)),
                ('loser_team', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('umpire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Myapp.umpire')),
            ],
        ),
    ]
