# Generated by Django 5.0.1 on 2024-03-15 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowler',
            name='player_ptr',
        ),
        migrations.RemoveField(
            model_name='captain',
            name='team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='loser_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='num_batsmen',
        ),
        migrations.RemoveField(
            model_name='team',
            name='num_bowlers',
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(to='Myapp.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_type',
            field=models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('allrounder', 'Allrounder')], default='na', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='statistics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='captain',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Myapp.player'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='Myapp.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='Myapp.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='Myapp.team'),
        ),
        migrations.DeleteModel(
            name='Batsman',
        ),
        migrations.DeleteModel(
            name='Bowler',
        ),
    ]
