# Generated by Django 5.0.1 on 2024-03-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_remove_bowler_player_ptr_remove_captain_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='wicketkeeper',
        ),
    ]
